name: Build and Push Image

run-name: Build and Push Image

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
  IMAGE_TAG: "ghcr.io/gagahsyuja/test-img:latest"

on:
  - push

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build --tag test-img .

      - name: List image
        run: docker image ls

      - name: Check image
        run: docker history test-img:latest

      - name: Login to GitHub Container Registry
        run: echo $GITHUB_TOKEN | docker login ghcr.io --username gagahsyuja --password-stdin

      - name: Tag image
        run: docker tag test-img $IMAGE_TAG

      - name: Push image
        run: docker push $IMAGE_TAG

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Stop and remove existing container
        run: docker compose down --rmi all

      - name: Start container
        run: docker compose up --detach

      - name: View running container
        run: docker ps

      - name: Check container
        run: curl --retry-delay 3 localhost:8080
